apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ml7wxjyo5-python
  janus-idp.io/tekton: ml7wxjyo5-python
  backstage.io/kubernetes-id: ml7wxjyo5-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ml7wxjyo5-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
